# -*- coding: utf-8 -*-
"""overall_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThfWtRiKKpCOR-C9XcAif8INVnq5Z2v5
"""

# ======================================================
# 🏆 Premier League Overall Points Predictor
# ======================================================

import streamlit as st
import pandas as pd
import joblib
import os

# ======================================================
# Page Config
# ======================================================
st.set_page_config(
    page_title="⚽ Overall Points Predictor",
    page_icon="🏆",
    layout="wide"
)

st.title("🏆 Premier League Overall Points Predictor")
st.markdown("Predict a team's **total points** based on their season stats!")

# ======================================================
# Load Model
# ======================================================
MODEL_FILENAME = "linear_regression_model.pkl"  # exact filename

@st.cache_resource
def load_model():
    try:
        model = joblib.load(MODEL_FILENAME)
        return model
    except FileNotFoundError:
        st.error(f"❌ '{MODEL_FILENAME}' not found! Make sure it's in the same folder as app.py.")
        st.stop()
    except Exception as e:
        st.error(f"❌ Failed to load model: {e}")
        st.stop()

model = load_model()
# ======================================================
# Input Features
# ======================================================
st.subheader("📋 Enter Team Details")

col1, col2, col3 = st.columns(3)

with col1:
    season_end_year = st.number_input("Season End Year", min_value=1990, max_value=2100, step=1)
    team = st.text_input("Team Name")

with col2:
    played = st.number_input("Matches Played", min_value=0, step=1)
    won = st.number_input("Matches Won", min_value=0, step=1)

with col3:
    lost = st.number_input("Matches Lost", min_value=0, step=1)
    drawn = st.number_input("Matches Drawn", min_value=0, step=1)

# ======================================================
# Prepare Input DataFrame
# ======================================================
input_data = pd.DataFrame({
    'season_end_year': [season_end_year],
    'team': [team],
    'played': [played],
    'won': [won],
    'lost': [lost],
    'drawn': [drawn]
})

# ======================================================
# Predict Points
# ======================================================
if st.button("🔮 Predict Total Points"):
    if team.strip() == "":
        st.warning("Please enter the team name.")
    else:
        try:
            predicted_points = model.predict(input_data)[0]
            st.success(f"🏅 Predicted Total Points: {predicted_points:.2f}")
        except Exception as e:
            st.error(f"Prediction failed: {e}")