# -*- coding: utf-8 -*-
"""LeagueApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSdiJ47numuDEwbd0VXUkWGeF43q9ev8
"""

# app.py
import streamlit as st
import joblib
import numpy as np
import os

# ==============================
# ⚽ Premier League Winner Predictor
# ==============================
st.set_page_config(page_title="⚽ League Winner Predictor", layout="wide")
st.title("🏆 Premier League Winner Predictor")

model = joblib.load("league_winner_model.pkl")

# ==============================
# 🧮 Input Section
# ==============================
st.write("### Enter Mid-Season Team Stats to Predict if They'll Win the League 🏆")

col1, col2 = st.columns(2)

with col1:
    played = st.number_input("Matches Played", min_value=0, max_value=38, value=19)
    won = st.number_input("Wins", min_value=0, max_value=38, value=12)
    drawn = st.number_input("Draws", min_value=0, max_value=38, value=3)
    lost = st.number_input("Losses", min_value=0, max_value=38, value=4)

with col2:
    gf = st.number_input("Goals For (GF)", min_value=0, max_value=150, value=40)
    ga = st.number_input("Goals Against (GA)", min_value=0, max_value=150, value=20)
    gd = st.number_input("Goal Difference (GD)", min_value=-100, max_value=150, value=20)
    points = st.number_input("Points", min_value=0, max_value=100, value=39)

# ==============================
# 🔮 Prediction Section
# ==============================
if st.button("🔮 Predict Winner Chance"):
    # Prepare input features (same order used during training)
    input_data = np.array([[played, won, drawn, lost, gf, ga, gd, points]])

    # Make prediction
    prediction = model.predict(input_data)[0]

    # Display result
    if prediction == 1:
        st.success("🏆 This team has a HIGH chance to win the league!")
    else:
        st.warning("⚽ This team is unlikely to win the league this season.")

# ==============================
# ℹ️ Notes
# ==============================
st.caption("Model trained using RandomForestClassifier on historical Premier League data (1993–2024).")